config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  get 'home/index'
  root to: "home#index"

  resources :professors , only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :hours ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :schedules ,  only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :works ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :groups ,     only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :tasks ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :students ,   only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :subjects ,   only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :docs 

  get 'say/new'
  get 'say/hello' 
  get 'say/goodbye'
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :subject
  has_many :schedule
  has_many :hour

end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/professor.rb
class Professor < ApplicationRecord
has_many :schedule

validates :name ,presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :group
  belongs_to :professor
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :hour
    has_many :work

    validates :name, presence: true
    validates :promedio, numericality: true

    mount_uploader :photo, PhotoUploader
end

app/models/subject.rb
class Subject < ApplicationRecord
has_many :task

validates :name ,presence: true
validates :name , uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :subject
  has_many :work

  validates :name, presence: true
  validates :doc, allow_blank: true, format:
   { with: %r{\.(doc|docx|png|jpg)\Z}i,
    message: 'Seleccione archivos  DOC,DOCX, JPG o PNG .'
   }

  mount_uploader :doc , DocUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :task
  belongs_to :student

  # validates :task_id, presence: true
  # validates :student_id, presence: true
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @Addition = "Profesor"
    @Concatenation = "cow" + "boy" 
    experiment
  end

  def experiment
    @Time_hour = 1.hour.from_now.localtime 
    
  end

  def goodbye
  end

  def new
  end

  def hola
  end
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/say/alumno.html.erb
<h1>Students</h1>
<br>


<%=form_for :student, url: students_path do |f| %>
    <%= f.label :Matricula %><br>
    <%= f.text_field  :matricula %><br>
    <%= f.label :Nombre %><br>
    <%= f.text_field  :name %><br>
    <%= f.label :Promedio %><br>
    <%= f.text_field  :promedio %><br>


    <%=f.submit%>
<% end%>

app/views/say/goodbye.html.erb
<h1>Adios Popo</h1>
<p>Vuelve Pronto xD</p>
<p>NO te vayas  <%= link_to "REGRESAR",say_hello_path%> !! </p>

app/views/say/hello.html.erb
<h1>Hola Project Tona</h1>
<p>
Que hora es Corazon <%=@time%>
</p>
<p><%= @Addition%></p>
<p><%= "cow" + "boy"%></p>



<p><%= @Time_hour%></p>


<p>
Hoara de irse
<%= link_to "Adios", say_goodbye_path %>!
</p>

app/views/say/hola.html.erb
<p>Hola desde el say</p>

app/views/say/new.html.erb
<h1>New file</h1>

<%=form_for :doc , url: docs_path do |f| %>
    <%= f.label :description %><br>
    <%= f.text_field  :description %><br>
    <%= f.label :student %><br>
    <%= f.text_field  :student %><br>
    <%= f.label :Materia %><br>
    <%= f.text_field  :materia %><br>


    <%=f.submit%>
<% end%>