config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  get 'home/index'
  root to: "home#index"

  resources :professors , only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :hours ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :schedules ,  only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :works ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :groups ,     only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :tasks ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :students ,   only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :subjects ,   only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :docs 

  get 'say/new'
  get 'say/hello' 
  get 'say/goodbye'
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :subject
  has_many :schedule
  has_many :hour

end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/professor.rb
class Professor < ApplicationRecord
has_many :schedule

validates :name ,presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :group
  belongs_to :professor
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :hour
    has_many :work

    validates :name, presence: true
    validates :promedio, numericality: true

    mount_uploader :photo, PhotoUploader
end

app/models/subject.rb
class Subject < ApplicationRecord
has_many :task

validates :name ,presence: true
validates :name , uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :subject
  has_many :work

  validates :name, presence: true
  validates :doc, allow_blank: true, format:
   { with: %r{\.(doc|docx|png|jpg)\Z}i,
    message: 'Seleccione archivos  DOC,DOCX, JPG o PNG .'
   }

  mount_uploader :doc , DocUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :task
  belongs_to :student

  # validates :task_id, presence: true
  # validates :student_id, presence: true
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = Doc.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doc_params
      params.require(:doc).permit(:description, :student, :materia)
    end
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/professor_helper.rb
module ProfessorHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/docs/_form.html.erb
<%= form_with(model: doc, local: true) do |form| %>
  <% if doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% doc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :student %>
    <%= form.text_field :student %>
  </div>

  <div class="field">
    <%= form.label :materia %>
    <%= form.text_field :materia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing Doc</h1>

<%= render 'form', doc: @doc %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Docs</h1>

<table>
  <thead>
    <tr>
      <th> description</th>
      <th>student</th>
      <th>Materia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= doc. description %></td>
        <td><%= doc.student %></td>
        <td><%= doc.materia %></td>
        <td><%= link_to 'Show', doc %></td>
        <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
        <td><%= link_to 'Destroy', doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>New Doc</h1>

<%= render 'form', doc: @doc %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> description:</strong>
  <%= @doc. description %>
</p>

<p>
  <strong>student:</strong>
  <%= @doc.student %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @doc.materia %>
</p>

<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>