config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  get 'home/index'
  root to: "home#index"

  resources :professors , only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :hours ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :schedules ,  only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :works ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :groups ,     only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :tasks ,      only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :students ,   only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :subjects ,   only: [:index, :create, :show, :destroy,:new,:edit,:update] 
  resources :docs 

  get 'say/new'
  get 'say/hello' 
  get 'say/goodbye'
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :subject
  has_many :schedule
  has_many :hour

end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/professor.rb
class Professor < ApplicationRecord
has_many :schedule

validates :name ,presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :group
  belongs_to :professor
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :hour
    has_many :work

    validates :name, presence: true
    validates :promedio, numericality: true

    mount_uploader :photo, PhotoUploader
end

app/models/subject.rb
class Subject < ApplicationRecord
has_many :task

validates :name ,presence: true
validates :name , uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :subject
  has_many :work

  validates :name, presence: true
  validates :doc, allow_blank: true, format:
   { with: %r{\.(doc|docx|png|jpg)\Z}i,
    message: 'Seleccione archivos  DOC,DOCX, JPG o PNG .'
   }

  mount_uploader :doc , DocUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :task
  belongs_to :student

  # validates :task_id, presence: true
  # validates :student_id, presence: true
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  
  before_action :find_professor, only: [:edit, :update, :show, :destroy]

  def new
    @professor = Professor.new
  end

  def index
    @professor =Professor.all
  end


  def create 
      @professor=Professor.new professor_paramns
    
      if @professor.save
      #debugger 
        return redirect_to professor_path
      end  
      reder :show
  end

  def show
    @professor = Professor.find params[:id ]
  end

  def edit
    @professor = Professor.find params[:id ]
  end

  def update
    #find_professor
    @professor.update professor_paramns
    redirect_to @professor
  end
  
  def destroy
    @professor.destroy
    redirect_to @professor
  end
  private

  def professor_paramns
      params.require(:professor).permit(:area,:name,:last_name)
  end

  def find_professor
    @professor =Professor.find params[:id]
  end
    
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/professor_helper.rb
module ProfessorHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/professors/_form.html.erb
<%=form_for @professor do |f| %>
    <%= f.label :Nombre %><br>
    <%= f.text_field  :name %><br>
    <%= f.label :Apellido %><br>
    <%= f.text_field  :last_name %><br>
    <%= f.label :area %><br>
    <%= f.text_field  :area %><br>
   

    <%=f.submit%>
<% end%>

app/views/professors/_professor.htmll.erb
<%= professor.name %> <br>

app/views/professors/edit.html.erb
<h1>Professor Edit</h1>
<br>


<%= render 'form' %>

app/views/professors/index.html.erb
<%= @professor.each do |professor| %>
    <%= professor.name %>
    <%= link_to 'Editar', edit_professor_path(professor) %>
    <%= link_to 'Eliminar', professor, method: :delete, data:{confirm: 'Seguro deseas eliminarlo?'} %>
    <br>
<% end %> 

app/views/professors/new.html.erb
<h1>Professor new</h1>
<br>


<%=form_for @professor, url: professors_path  do |f| %>
    <%= f.label :Matricula %><br>
    <%= f.text_field  :matricula %><br>
    <%= f.label :Nombre %><br>
    <%= f.text_field  :name %><br>
    <%= f.label :Apellido %><br>
   

    <%=f.submit%>
<% end%>

app/views/professors/show.html.erb
<p>El nombre del professor es </p>
<%= @professor.name %>